# Generated by Django 4.0.3 on 2024-02-06 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesperson',
            options={'ordering': ['employee_id']},
        ),
    ]
